### ISSUE TITLE
Issues with PackageLocator().ProbeBinFolderAssemblies();

### ISSUE THREAD

**Issue by cajuncoding** [Bikeman868/Ioc.Modules#1]
We have an application for which I'm trying to use UrlRewrite.Net (an excellent solution by the way).  However, our application requires the use of a Platform API that has dll dependencies that are not all managed code.  To be specific it requires that a file called xmogrt.dll (from the JuggerNet Java proxy project) to be in our bin folder of the application!  

This fails when the method ProbeBinFolderAssemblies() runs with an exception saying "BadImageFormatException: Could not load file or assembly 'xmogrt' or one of its dependencies. The module was expected to contain an assembly manifest." because it's not a managed .Net dll assembly.

Is there  away to provide a set of dll files to IGNORE?  Looking at the source code I don't see one.  If not then there should be a try/catch block to handle these types of errors because they are bound to happen when generically ripping through all dll's in a bin folder.

Would appreciate your thoughts on this -- for now I'll have to pull the source and modify to exclude known problemmatic (e.g. non-managed dll's).  Thanks!

**Comment by Bikeman868** [comment]
As you correctly identified, this the behavior of the default factory in `UrlRewrite`, and not an issue with `Ioc.Modules`. See the `UrlRewrite` project issues for my full reply.

I am not a big fan of catching exceptions in situations like this, it can make it difficult to figure out why things are not working as expected. The `PackageLocator()` provides a number of other methods of registering assemblies that should cater to any situation.
